import type { Metadata, Viewport } from "next";
import { Inter, Hind_Siliguri } from "next/font/google";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
import { Analytics } from "@/components/Analytics";
import { ServiceWorker } from "@/components/ServiceWorker";
import { JsonLd } from "@/components/JsonLd";
import {
  DEFAULT_OG_IMAGE,
  SITE_NAME,
  SITE_TITLE,
  organizationJsonLd,
  siteUrl,
  websiteJsonLd,
} from "@/lib/seo";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const hindSiliguri = Hind_Siliguri({
  variable: "--font-hind-siliguri",
  subsets: ["bengali", "latin"],
  weight: ["400", "500", "600", "700"],
});

const DESCRIPTION =
  "BdAIO is the national AI Olympiad for Bangladeshi students — a pathway to international competitions like IOAI and IAIO.";

export const metadata: Metadata = {
  // Without metadataBase, every relative Open Graph image resolves against
  // localhost in production and social previews silently break.
  metadataBase: new URL(siteUrl()),
  title: {
    default: SITE_TITLE,
    template: `%s | ${SITE_NAME}`,
  },
  description: DESCRIPTION,
  applicationName: SITE_NAME,
  keywords: ["BdAIO", "AI Olympiad", "Bangladesh", "Artificial Intelligence", "IOAI", "IAIO"],
  // Defaults every page inherits; pageMetadata() overrides them per page.
  openGraph: {
    type: "website",
    siteName: SITE_NAME,
    title: SITE_TITLE,
    description: DESCRIPTION,
    url: siteUrl(),
    locale: "en_US",
    images: [{ url: DEFAULT_OG_IMAGE, width: 1200, height: 630 }],
  },
  twitter: {
    card: "summary_large_image",
    title: SITE_TITLE,
    description: DESCRIPTION,
    images: [DEFAULT_OG_IMAGE],
  },
  icons: {
    // src/app/icon.png is picked up automatically; these are the installable
    // and iOS variants generated by scripts/generate-brand-assets.mjs.
    icon: [
      { url: "/icon-192.png", sizes: "192x192", type: "image/png" },
      { url: "/icon-512.png", sizes: "512x512", type: "image/png" },
    ],
    apple: [{ url: "/apple-icon.png", sizes: "180x180", type: "image/png" }],
  },
  // Points at app/manifest.ts, which makes the site installable.
  manifest: "/manifest.webmanifest",
};

export const viewport: Viewport = {
  // Tints the browser chrome on Android and the status bar in standalone mode.
  themeColor: "#026f89",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      data-scroll-behavior="smooth"
      className={`${inter.variable} ${hindSiliguri.variable} h-full antialiased`}
    >
      <body className="flex min-h-full flex-col">
        {/* Site-wide structured data. Page-level entities (Event, Person,
            EducationalOrganization) are added by the pages themselves. */}
        <JsonLd data={organizationJsonLd()} />
        <JsonLd data={websiteJsonLd()} />
        <Header />
        <main className="site-main flex-1">{children}</main>
        <Footer />
        <Analytics />
        <ServiceWorker />
      </body>
    </html>
  );
}
